spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-dispatch-service
              uri: lb://ORDER-DISPATCH-SERVICE
              predicates:
                - Path=/api/v1/order/**

            - id: trip-telemetry-service
              uri: lb://TRIP-TELEMETRY-SERVICE
              predicates:
                - Path=/api/v1/trip/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notification/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
server:
  port: 7000